[package]
name = "mcp-client-sse"
version = "0.1.0"
edition = "2021"

[dependencies]
mcp-core = { path = "../mcp-core" }
mcp-transport-sse = { path = "../mcp-transport-sse" }
mcp-types = { path = "../mcp-types" }
