[package]
name = "mcp-types"
version = "0.1.0"
edition = "2021"
authors = ["Collin Brittain <collin@iqlusion.io>"]

[dependencies]
jsonschema = "0.28.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

[dev-dependencies]
serde_json = "1.0.138"

[build-dependencies]
prettyplease = "0.2.29"
schemars = "0.8.21"
serde_json = "1.0.138"
syn = "2.0.96"
typify = "0.3.0"
